// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from "prisma/config";
import dotenv from "dotenv";
dotenv.config();
export default defineConfig({
  schema: "../database/prisma/schema.prisma",
  migrations: {
    path: "../database/prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
